### ISSUE TITLE
AssetMix load error

### ISSUE THREAD

**Issue by kanava-ali** [ishanvyas22/asset-mix#30]
![image](https://user-images.githubusercontent.com/84898918/125281998-92201700-e31f-11eb-83ad-3ee863773428.png)

When I execute "npm run dev" I get this error. I have loaded the AssetMix helper in the AppView file also.

**Comment by ishanvyas22** [comment]
Have you generated the scoffoldings using [`generate` command](https://github.com/ishanvyas22/asset-mix#generate-command)? Or manually did it?

Also did you faced any issues while performing installation and configuration steps?

**Comment by kanava-ali** [comment]
I generated scaffolding using generate command. During installation I had
problem with outdated dependencies which was solved with force fix ... I
also had to to remove the --hide-modules parameter from mom run dev in
order to overcome a webpack related issue.

**Comment by ishanvyas22** [comment]
Got it. I was able to reproduce this issue.

Looks like you ran `npm audit fix --force`, it upgraded `laravel-mix` to version 6.x. So as a breaking change in Laravel Mix v6, you need to update your npm script as described in upgrade guide: https://laravel-mix.com/docs/6.0/upgrade#update-your-npm-scripts. Also you have to make few changes in your `webpack.mix.js` file in order to make it work properly.

To resolve "Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders" error, you need to add `.vue({ version: 2 })` as suggested at https://github.com/JeffreyWay/laravel-mix/issues/2766#issuecomment-766462863.

I hope this will solve your problem for this issue. Also, I think it's time that we upgrade Laravel Mix version to 6.x so I'll plan it once I get chance.
